### ISSUE TITLE
DDC tab

### ISSUE THREAD

**Issue by L0FKA** [rscustom/rocksmith-custom-song-toolkit#250]
I have found a few issues with the DDC tab of the RSToolkit when I generate DD on a set of psarc files :
- If an error occurs, the DDC tab is blocked and I need to restart the RST
- Sometimes I have an error like : "File already exists" (you can try with the CDLC : "Faith No More - A Small Victory")
- When DDC is launched the shell window is displayed

Thank you

**Comment by cozy1** [comment]
@L0FKA Fixed here https://github.com/rscustom/rocksmith-custom-song-toolkit/commit/09cbf45082f420d2a086cd8e5c55414fd5d2be30  Would appreciate your testing.  Before issue is closed.

**Comment by L0FKA** [comment]
Not fixed yet ;)

**Comment by cozy1** [comment]
Faith No More - A Small Victory is DF song.  He puts watermarks into archive which toolkit and DDC can not interpret.  IMHO This is song issue not toolkit/DDC issue.  Other two issues are fixed unless you say otherwise.

**Comment by L0FKA** [comment]
"If an error occurs, the DDC tab is blocked and I need to restart the RST"

NOT fixed yet this what I mean, all points should be done I guess

**Comment by cozy1** [comment]
@L0FKA Is this issue fixed in the latest beta?

**Comment by cozy1** [comment]
@L0FKA  can we close this?

**Comment by L0FKA** [comment]
Let me ask someone who know :D but seems ok for me anyway :)

**Comment by cozy1** [comment]
No response from someone who knows, so no longer an issue.
